name = "directory-example"
main = "worker.ts"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "directory.example.com.ai/*", zone_name = "example.com.ai" }
]

[vars]
API_NAME = "directory.example.com.ai"

[[d1_databases]]
binding = "DB"
database_name = "directory-example-db"
database_id = ""

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "directory-example"
