name = "api-example"
main = "worker.ts"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "api.example.com.ai", custom_domain = true }
]

[vars]
API_NAME = "api.example.com.ai"

[[d1_databases]]
binding = "DB"
database_name = "api-example-db"
database_id = ""

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "api-example"
